# Generated by Django 6.0.2 on 2026-03-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_otp"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OTP",
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
