# Generated by Django 6.0.2 on 2026-03-29 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_delete_otp_user_address"),
        ("parking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cashiers",
                to="parking.parkingsite",
            ),
        ),
    ]
