# Generated by Django 6.0.2 on 2026-03-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("parking_owner", "Parking Owner"),
                    ("cashier", "Cashier"),
                    ("user", "User"),
                    ("entry_cashier", "Entry Cashier"),
                    ("exit_cashier", "Exit Cashier"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
