# Generated by Django 4.2 on 2026-06-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerRegistrationQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('query_type', models.CharField(choices=[('owner_registration', 'Request Parking Owner Account Registration'), ('general_support', 'General Support')], default='general_support', max_length=30)),
                ('proposed_site_name', models.CharField(blank=True, default='', max_length=200)),
                ('site_capacity', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'owner_registration_queries',
                'ordering': ['-created_at'],
            },
        ),
    ]
