# Generated by Django 4.2 on 2026-06-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_ownerregistrationquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerregistrationquery',
            name='admin_response',
            field=models.TextField(blank=True, default='', help_text="Admin's response to the query (for general support queries)"),
        ),
        migrations.AlterField(
            model_name='ownerregistrationquery',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=10),
        ),
    ]
