# Generated by Django 6.0.2 on 2026-02-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="extended_exit_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="extension_count",
            field=models.IntegerField(default=0),
        ),
    ]
