# Generated by Django 6.0.2 on 2026-03-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_booking_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("cash", "Cash"), ("online", "Online")],
                max_length=20,
                null=True,
            ),
        ),
    ]
