# Generated by Django 6.0.2 on 2026-03-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_booking_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
