# Generated by Django 6.0.2 on 2026-03-31 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_booking_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="updated_at",
        ),
    ]
