# Generated by Django 6.0.2 on 2026-02-21 07:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image_url", models.TextField()),
                ("detected_plate_number", models.CharField(max_length=20)),
                (
                    "confidence_score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                ("processed_model_name", models.CharField(max_length=50)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entry_exit_point",
                    models.CharField(
                        blank=True,
                        help_text="Camera location or entry/exit gate name",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_logs",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "db_table": "ai_logs",
                "indexes": [
                    models.Index(
                        fields=["detected_plate_number"],
                        name="ai_logs_detecte_f6859b_idx",
                    )
                ],
            },
        ),
    ]
