# Generated by Django 6.0.2 on 2026-03-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_module", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CameraAPIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("camera_name", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "camera_api_keys",
            },
        ),
    ]
