# Generated by Django 6.0.2 on 2026-03-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_module", "0002_cameraapikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="ailog",
            name="vehicle_type",
            field=models.CharField(blank=True, default="car", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="ailog",
            name="image_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
