# Generated by Django 6.0.2 on 2026-03-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_module", "0003_ailog_vehicle_type_alter_ailog_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="ailog",
            name="log_type",
            field=models.CharField(
                choices=[("entry", "Entry"), ("exit", "Exit")],
                default="entry",
                max_length=10,
            ),
        ),
    ]
