# Generated by Django 4.2 on 2026-05-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_module', '0004_ailog_log_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ailog',
            name='assigned_slot',
            field=models.CharField(blank=True, help_text='Slot reserved at detection time, before cashier approval', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ailog',
            name='cropped_plate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ailog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='cameraapikey',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
